# Generated by Django 4.0.3 on 2022-03-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_status',
        ),
    ]
