# Generated by Django 4.0.3 on 2022-03-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_remove_vehicle_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerecord',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapprove'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
    ]
